# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZpynzBXLOhLRgBHgMcKEkoboGj57Zn3di2HbbcWyu3A=,iv:lkNGU9gBoRm7inZrg/9RJqdSGqBH2MwMobhOVQIEN1o=,tag:KZB4Oaa97nRJdE86syY95g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1f6dfpwaaysj2zg5xs7f5d82njggesqnsvcuzpz30kvcy2dte7glsrrn43t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTy9mT2ZFZTdJQklrQ0xG
        RThVUVFBdmJDeU5zNmcrbDBTeUdIUkdCaVRjClAxZzEzZzFKaXowSmlUR0RoV2Rn
        dVdDV2txOUxKbjB3MmlCMWVYSkVlRkUKLS0tIExwNzdQZlIvbGxQblJNQXkyM3Fk
        eUhxVUxHUm5ya2ZYVC9Qb3ZEeFlLT1EKpJcHnv/5gWjYU11QHpqeBbispX7vpsKC
        VIXZr7o8h5r+1KGHde6jYH79cPu1CXBQZAbzfvyR0BQt6KWmYf2eaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-15T21:40:54Z"
  mac: ENC[AES256_GCM,data:moAlRV7g5gc+ermRic/yIM1MFw2wnUBSVc/75xueVDdROuhd+ZFDwj0N815Ycfgzxsa9VvUBlcne8ztWhd2sWVHW6+jDduSbTi4tQobx7kJiRCH/6/aTXPkLb6/AP4on8Yx9FQSsz+InV7Ris3deSvbPDp8UEaEDjtvoWsSUQEM=,iv:+W9IYp/CyoicQ6PMqKywIQbrZLxFUnhLO8HVGnnvUJg=,tag:pfU9lcVfSO9udbYsjss3bw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
