# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:kjuNwBzAVpXUmugUutiMZA5FJMnWVCDk+P5lUUjKzy4hDQMW,iv:sNFAdmiapULMzyQ2sH74rn/kVt03Af7ojSDSBTFF0a0=,tag:ggPefW69sFmUf9dEVaug1A==,type:str]
  credentials.json: ENC[AES256_GCM,data:ZuETP/AQn56l6q36mhCjbcvYHYe28cLSUXIocZ8j8yyAdsYIuRa63e/w5cWz4O0a1q3wNgqzjijJsTtOP66w5ColzPnZku12ZTcPui9wQI1UwuSvqEwrMfNJbYkXI7Jy3ZsdRiJeCcE32mA9EN6LtYK8RqnteTWjLXw74qiLtDzxmQlpm195hVYwPOxI56EbK/LmRhNeH4sVuWDM0Ipvrx04MPPEmaIjoNKr0ey4xA==,iv:cqZqGJ6osLcNRMTDR7UaDwvNPDdl0x5ccjhIyNv8yzE=,tag:6J0uJ4yOb7RS8VUCJYYQBw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1f6dfpwaaysj2zg5xs7f5d82njggesqnsvcuzpz30kvcy2dte7glsrrn43t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRHlDYmZXWTRaSDRvOHFU
        Vm9SdWptRjJvUlBzUlpEczNmWVdtOXgvVVhvCkxmSGFtT1NsZTk4N1VlMzV2YkFO
        aXBDMHBuYVV5aEI2YUtPcDZlL0F1WWsKLS0tIHU5aEEvTHhpc1BvODRjSlQ1U0pS
        bW5qbzh6K1grTkhQOW9JdVVIbjJLUVEKD1LpYEZCng5QRAqsDbEehhuijz8rIPKP
        oLA4qqoI/19fSdOWBjlWF7JQeCdUJYZmYHhCO8MqQMC4GuVimt0hBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-15T21:40:54Z"
  mac: ENC[AES256_GCM,data:RpHbCccoN+pR7ICxFOaJuQ8gEHmPFPpgBWCv6Z7CHJtEj1nDR6a2ZEOtoEIbTO6fIteFU4ybIMS5mtDGgtI6FH3l3OrghRbnsf0FztI0rB4sa0yed6GKIZQ4QlT8HYFEimcvVOZZnG4LodEVeyG2oPGT6gVteUBLTxgJ3igBmaU=,iv:ODc8DEbBQWA8xPbB+Wlcy3N6pMmmcQZKmRfInqMfPoA=,tag:PM9SoHz+7TV+NTNKs8KIXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
