# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:U8TGbRtD5JZZBUo=,iv:AvkvlxQA3W4lvYbkKECgn8U60SVv1JK+LIbTwbyJ9CA=,tag:SZ/H/wkt+ljUTfJnlfj9Dg==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jUbWsEOQ0pesuuJmD07kUF250sd4c28=,iv:j/WR7itgeQgDgK31kSnp9UwBZIHB1+Itc3w9uGCwmBg=,tag:2knMI5hD20ugfpZP9uS0Fw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bkadlIVSMgQOuTHSGbpj0Q+mZX1tg6W1FWyDvHAmHtVgYiRa,iv:v1rmjp29eDtpaoSNmGtjgVGhgHMJ92KVw37rGcRU9iI=,tag:Q1d6p3bg98k37cufp7cftA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1f6dfpwaaysj2zg5xs7f5d82njggesqnsvcuzpz30kvcy2dte7glsrrn43t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTTljMGpqMXRTOG9Nbk5P
        THA0eDhPWTNJVWpGUnprcHQzUis4WmpZT0NzCkVMMmF0MkZZOTJkck1OeGpFaStG
        R0ZjKzBlWUVVc2o5c2VYOVNMMmF4ZDgKLS0tIHFZSy9CcjB1ZkgvNHk0cERqUjlX
        ZEVOM0VvbmRRQm5URUZZa3V0ekRSeGcKj9S5+PpjGD791TO8rHnRqIqamIRRQv+2
        UDNfYijqxga9N3I0behv1cduHsjAk8jWYr5nUAGui2Q3zHAHZRGqqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-16T05:06:44Z"
  mac: ENC[AES256_GCM,data:Q1GbD4MszfA4WS3EUTVaG/LiHN+IY6nduswdON4Lv86BorfKWQiuU23J0wOB2sK+SWsIVIyyRZxFcxw024okrWePI1RmyZ2WbeVVa5jljIKh33r6uczUgiQcpA9mBPGcH0dsIkbsTWeb/EDkTUYa2p1Cl3L85PDdZUuNjiEqu3g=,iv:r+S/bhbVBcoUGdw62QlrMDiyZEQHmZNqbC/Tu736iVo=,tag:nijGfokfNMvFd4AqB5RtGg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
