# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:wtxkpFFn4ll/wqSF43MUqX2lprrqALNBbTweSE9yVYC6b6K407Zsbw==,iv:/5cekgC51Grb8SPMT01PFoKHIN8WOWtcy7qAOu5T700=,tag:3CsSeDxJLiaH2VBSTbxeyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1f6dfpwaaysj2zg5xs7f5d82njggesqnsvcuzpz30kvcy2dte7glsrrn43t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aDB5dVBvTFZKTCt2a2Fr
        bkhKMDgvN1VJYmFFZHdyRm9pSE9vUVBuZW4wCmFJcFlOWnIwS3dsQTB2ZWtDem1O
        cjNwMlNVazZMVGtVdFIwVk8vRnp4bEUKLS0tIHVPNkY1MTVJWUJyNWMvRWRVZEFM
        OVVINUV4RjVUMHBYbG42dlc0VVlRdHcKcJApd9ue/Nv31qNLoSzo0CBnAO12W36u
        9SnrhJZuNrixRn+jXf4I0n42w88xmPxlTXmBp5rkbwmHKDgqPe3Lsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-16T05:06:44Z"
  mac: ENC[AES256_GCM,data:q2yReZ5m46n4mD7xni4ovqMwP8XFUFZ+8XWhuwDib/c8snPp+70C2Kvo4d8hTXjxdBUBT/2pGhN+O8NXO8RLx1ywDky5uY3MBv4KnbelQXjV5q2GuGuJ3ksKnUyqoOBCSdHzwoTsXYBTUhsLvRhqA5x/XmozDeCATYgxgN2EQBI=,iv:rIHpV03h+v2xPxjn6zCXa9yfUALflANbXlVWVdt4WSE=,tag:QlfRkDLlTXw7mk3YADICag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
